
// This file is no longer used as quiz questions are dynamically generated by AI.
// You can safely delete this file.
// Keeping it temporarily just to fulfill the XML change requirement if needed by the system,
// but its content is irrelevant.

export interface QuizQuestion {
  id: string;
  questionText: string;
  options: string[];
  correctAnswer: string;
}

export const quizQuestions: QuizQuestion[] = [];
